services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pkt-monthly-record-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pkt_user
      POSTGRES_PASSWORD: pkt_secure_password_2024
      POSTGRES_DB: monthly_records
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - pkt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pkt_user -d monthly_records"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pkt-monthly-record-app
    restart: unless-stopped
    environment:
      # Database
      DATABASE_URL: "postgresql://pkt_user:pkt_secure_password_2024@postgres:5432/monthly_records"
      
      # NextAuth
      NEXTAUTH_SECRET: "your-super-secret-nextauth-key-change-this-in-production"
      NEXTAUTH_URL: "http://localhost:5000"
      
      # Node Environment
      NODE_ENV: "production"
      
      # Next.js
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "5000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pkt-network
    volumes:
      - ./prisma:/app/prisma
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional - for production with SSL)
  nginx:
    image: nginx:alpine
    container_name: pkt-monthly-record-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - pkt-network
    profiles:
      - production

volumes:
  postgres_data:
    driver: local

networks:
  pkt-network:
    driver: bridge
